version: '3'

networks:
  thoughts-beta-network:
    driver: bridge

volumes:
  prometheus_data: {}
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
    - ./data/db_data:/var/lib/mysql
    - ./config/mysql/init:/docker-entrypoint-initdb.d/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flash_sale
      MYSQL_USER: thoughts-beta
      MYSQL_PASSWORD: thoughts-beta
    ports:
    - 13306:3306
    networks:
    - thoughts-beta-network

  redis:
    container_name: redis
    image: redislabs/redismod:latest
    ports:
    - 16379:6379
    volumes:
    - ./data/redis:/data #数据文件挂载
    networks:
    - thoughts-beta-network


  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    volumes:
    - ./config/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
    - thoughts-beta-network

  logstash:
    image: logstash:7.14.2
    container_name: logstash
    volumes:
    - ./config/elk/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./config/elk/pipeline:/usr/share/logstash/pipeline
    ports:
    - "5044:5044"
    - "5000:5000/tcp"
    - "5000:5000/udp"
    - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - thoughts-beta-network
    depends_on:
    - elasticsearch

  kibana:
    image: kibana:7.14.2
    container_name: kibana
    volumes:
    - ./config/elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - "5601:5601"
    networks:
    - thoughts-beta-network
    depends_on:
    - elasticsearch


  rmqnamesrv:
    image: foxiswho/rocketmq:server
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/rmqnamesrv/logs:/opt/logs
      - ./data/rmqnamesrv/store:/opt/store
    networks:
      - thoughts-beta-network

  rmqbroker:
      image: foxiswho/rocketmq:broker
      container_name: rmqbroker
      ports:
        - 10909:10909
        - 10911:10911
      volumes:
        - ./data/rmqbroker/logs:/opt/logs
        - ./data/rmqbroker/store:/opt/store
        - ./config/rocketmq/broker.conf:/etc/rocketmq/broker.conf
      environment:
        NAMESRV_ADDR: "rmqnamesrv:9876"
        JAVA_OPTS: " -Duser.home=/opt"
        JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
      command: mqbroker -c /etc/rocketmq/broker.conf
      depends_on:
        - rmqnamesrv
      networks:
        - thoughts-beta-network

  rmqconsole:
      image: styletang/rocketmq-console-ng
      container_name: rmqconsole
      ports:
        - 8080:8080
      environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
      depends_on:
        - rmqnamesrv
      networks:
        - thoughts-beta-network


